apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.localStorageClass.name | quote }}
  annotations: 
    {{- if .Values.localStorageClass.isDefault }}
    "storageclass.kubernetes.io/is-default-class": "true"
    {{- end }}
reclaimPolicy: {{ .Values.localStorageClass.reclaimPolicy | quote }}
provisioner: kubernetes.io/no-provisioner
